<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../CashCafe.Data/CashCafe.Data.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="CashCafe.Backup.Tests" />
  </ItemGroup>
</Project>
