<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../CashCafe.Data/CashCafe.Data.csproj" />
    <ProjectReference Include="../CashCafe.Excel/CashCafe.Excel.csproj" />
    <ProjectReference Include="../CashCafe.Backup/CashCafe.Backup.csproj" />
  </ItemGroup>
</Project>
